openapi: 3.0.3
info:
  title: OrderServiceApi
  version: 1.0.0
  description: Api для работы с заказами
x-ogen:
  target: ./shared/pkg/openapi/order/v1
  package: order_v1
  clean: true

tags:
  - name: Order
    description: Операции с заказами. Создание, получение, оплата, отмена

paths:
  /api/v1/orders: # POST /api/v1/orders — создание заказа
    $ref: "./paths/orders.yaml"
  /api/v1/orders/{order_uuid}/pay: #POST /api/v1/orders/{order_uuid}/pay — оплата заказа
    $ref: "./paths/order_pay.yaml"
  /api/v1/orders/{order_uuid}: # GET /api/v1/orders/{order_uuid} — получить заказ по UUID
    $ref: "./paths/order_by_uuid.yaml"
  /api/v1/orders/{order_uuid}/cancel: # POST /api/v1/orders/{order_uuid}/cancel
    $ref: "./paths/order_cancel.yaml"